name: Deploy Starter Folder to GitHub Pages

on:
  push:
    branches:
      - main  # Change 'main' to 'master' if your branch is master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./starter  # THIS IS THE CRITICAL LINE
          # You can change 'pages' to 'gh-pages' if needed, but 'pages' is standard
